# Generated by Django 4.1.5 on 2023-05-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 'Bad'), (2, 'Poor'), (3, 'Okay'), (4, 'Good'), (5, 'Excellent')]),
        ),
    ]
